#!/usr/bin/env bash
#
# Build the fat jar and deploy it to an IBM i over scp, along with the tools/
# directory, a PASE launcher, and a Service Commander definition installed to
# ~/.sc/services/mcp_server_lite.yaml on the target. After deploying:
#
#   ssh <user@host>
#   sc start mcp_server_lite
#
# The service runs with --transport http (sc manages daemons; stdio clients
# should launch the jar directly). Artifacts mirror packaging/ibmi/, adapted
# to the chosen deploy directory instead of the RPM's /QOpenSys/pkgs paths.
#
# Usage: scripts/deploy-ibmi.sh <user@host> [deploy-dir]
#   deploy-dir defaults to ibmi-mcp-server-lite under the remote $HOME.
#   A relative deploy-dir resolves against the remote $HOME. Don't use ~ —
#   your local shell expands it to your local home before the script runs.
#
# If a local .env exists it is copied to the deploy dir (the launcher passes
# --env-file <deploy-dir>/.env); otherwise create one on the IBM i with the
# DB2i_* connection settings (see .env.example).

set -euo pipefail

usage() {
  echo "Usage: $(basename "$0") <user@host> [deploy-dir]" >&2
  exit 1
}

[ $# -ge 1 ] || usage
TARGET=$1
DEPLOY_DIR=${2:-}

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ssh auth: prefer keys; if key auth fails, fall back to the DB2i_PASS from
# .env (the IBM i profile password) via sshpass -e (password stays out of argv).
SSH=(ssh)
SCP=(scp)
if ! ssh -o BatchMode=yes -o ConnectTimeout=8 "$TARGET" true 2>/dev/null; then
  PASS=$(sed -n 's/^DB2i_PASS=//p' "$REPO_ROOT/.env" 2>/dev/null | head -1)
  PASS=${PASS%\"}; PASS=${PASS#\"}; PASS=${PASS%\'}; PASS=${PASS#\'}
  if [ -n "$PASS" ] && command -v sshpass >/dev/null; then
    echo "==> Key auth unavailable — using DB2i_PASS from .env via sshpass"
    export SSHPASS="$PASS"
    SSH=(sshpass -e ssh)
    SCP=(sshpass -e scp)
  elif [ -n "$PASS" ]; then
    echo "note: key auth unavailable and sshpass not installed — you will be prompted for the ssh password." >&2
  fi
fi

if [ -n "${HOME:-}" ] && [ "${DEPLOY_DIR#"$HOME"}" != "$DEPLOY_DIR" ]; then
  echo "error: deploy dir $DEPLOY_DIR is under your local home — '~' was expanded by your local shell." >&2
  echo "Pass a remote-absolute path (e.g. /home/USER/mcp) or a relative one (mcp)." >&2
  exit 1
fi
if [ -z "$DEPLOY_DIR" ]; then
  DEPLOY_DIR="$("${SSH[@]}" "$TARGET" 'echo $HOME')/ibmi-mcp-server-lite"
elif [ "${DEPLOY_DIR#/}" = "$DEPLOY_DIR" ]; then
  DEPLOY_DIR="$("${SSH[@]}" "$TARGET" 'echo $HOME')/$DEPLOY_DIR"
fi

echo "==> Building (mvnw package)"
(cd "$REPO_ROOT" && ./mvnw package)

JAR=$(find "$REPO_ROOT/target" -maxdepth 1 -name 'ibmi-mcp-server-lite-*.jar' ! -name 'original-*' | head -n 1)
[ -n "$JAR" ] || { echo "error: shaded jar not found in target/" >&2; exit 1; }

echo "==> Staging artifacts for $TARGET:$DEPLOY_DIR"
STAGE=$(mktemp -d)
trap 'rm -rf "$STAGE"' EXIT

cp "$JAR" "$STAGE/ibmi-mcp-server-lite.jar"
cp -R "$REPO_ROOT/tools" "$STAGE/tools"

HAVE_ENV=false
if [ -f "$REPO_ROOT/.env" ]; then
  cp "$REPO_ROOT/.env" "$STAGE/.env"
  HAVE_ENV=true
fi

# PASE launcher — QIBM_* stdio settings match packaging/ibmi/ibmi-mcp-server-lite.sh.
cat > "$STAGE/mcp_server.sh" <<EOF
#!/QOpenSys/usr/bin/sh
# Generated by scripts/deploy-ibmi.sh — launcher for ibmi-mcp-server-lite.
DIR=$DEPLOY_DIR
JAVA=\${JAVA:-/QOpenSys/QIBM/ProdData/JavaVM/jdk17/64bit/bin/java}

QIBM_JAVA_STDIO_CONVERT=N \\
QIBM_PASE_DESCRIPTOR_STDIO=B \\
QIBM_USE_DESCRIPTOR_STDIO=Y \\
QIBM_MULTI_THREADED=Y \\
exec "\$JAVA" -jar "\$DIR/ibmi-mcp-server-lite.jar" \\
  --tools "\$DIR/tools" --env-file "\$DIR/.env" "\$@"
EOF
chmod +x "$STAGE/mcp_server.sh"

# Service Commander definition; filename gives the short name
# (sc start mcp_server_lite) — distinct from the agent app's mcp_server.
# YAML_* flags are required for directory tool loads (every pack defines ibmi-system)
# and win over .env because process environment takes precedence.
cat > "$STAGE/mcp_server_lite.yaml" <<EOF
# Generated by scripts/deploy-ibmi.sh — Service Commander definition for
# ibmi-mcp-server-lite deployed at $DEPLOY_DIR.
name: IBM i MCP Server Lite
dir: $DEPLOY_DIR
# Port 3014 (not the 3010 default) to stay clear of other MCP deployments.
start_cmd: $DEPLOY_DIR/mcp_server.sh --transport http --no-reload --http-port 3014
check_alive: '3014'
batch_mode: 'true'
sbmjob_opts: 'JOBQ(QUSRNOMAX)'
environment_vars:
  - PATH=/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
  - YAML_MERGE_ARRAYS=true
  - YAML_ALLOW_DUPLICATE_SOURCES=true
EOF

echo "==> Copying to $TARGET"
"${SSH[@]}" "$TARGET" "mkdir -p '$DEPLOY_DIR' \"\$HOME/.sc/services\""
SCP_FILES=("$STAGE/ibmi-mcp-server-lite.jar" "$STAGE/mcp_server.sh" "$STAGE/tools")
$HAVE_ENV && SCP_FILES+=("$STAGE/.env")
"${SCP[@]}" -r "${SCP_FILES[@]}" "$TARGET:$DEPLOY_DIR/"
"${SCP[@]}" "$STAGE/mcp_server_lite.yaml" "$TARGET:.sc/services/mcp_server_lite.yaml"

HOST=${TARGET#*@}
echo
echo "Deployed to $TARGET:$DEPLOY_DIR"
$HAVE_ENV || echo "NOTE: no local .env found — create $DEPLOY_DIR/.env on the IBM i with the DB2i_* settings (see .env.example) before starting."
cat <<EOF

Next steps:
  ssh $TARGET
  sc start mcp_server_lite             # submits the daemon (JOBQ QUSRNOMAX)
  sc check mcp_server_lite             # status
  curl http://$HOST:3014/healthz      # pool health probe
  sc stop mcp_server_lite              # stop (run before redeploying)
EOF
